In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r'C:\Users\Rohit\OneDrive\Desktop\Python DS UPGRAD\CreditCard\creditcard.csv')

In [3]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
data.isnull().sum(axis=0)

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [6]:
data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [7]:
#Highly imbalanced data

In [8]:
data.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  3.918649e-15  5.682686e-16 -8.761736e-15  2.811118e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean  -1.552103e-15  2.040130e-15 -1.698953e-15 -1.893285e-16 -3.147640e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.473120e-16  8.042109e-16  5.282512e-16  4.456271e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   1.426896e-15  1.701640e-15 -3.662252e-16 -1.217809e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

In [10]:
X=data.drop('Class',axis=1)
y=data['Class']

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [ ]:
#Logistic Regression

In [19]:
logreg=LogisticRegression()
kfold=KFold(n_splits=5,random_state=None)
grid={'penalty':['l1','l2'],'C':10.0 ** np.arange(-2,3)}

In [21]:
logmodel=GridSearchCV(estimator=logreg,param_grid=grid,cv=kfold,n_jobs=-1)

In [22]:
logmodel.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan 0.99884633        nan 0.99884132        nan 0.99891154
        nan 0.99884633        nan 0.99888144]
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']})

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [24]:
y_test_pred=logmodel.predict(X_test)

In [25]:
print(accuracy_score(y_test,y_test_pred))
print(confusion_matrix(y_test,y_test_pred))
print(classification_report(y_test,y_test_pred))

0.9988764439450862
[[85243    39]
 [   57   104]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85282
           1       0.73      0.65      0.68       161

    accuracy                           1.00     85443
   macro avg       0.86      0.82      0.84     85443
weighted avg       1.00      1.00      1.00     85443



In [26]:
#DecisionTree

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [29]:
params={'max_depth': range(5, 25, 5),
    'min_samples_leaf': range(50, 250, 50),
    'min_samples_split': range(50, 250, 50),
    'criterion': ["entropy", "gini"]}
tree=DecisionTreeClassifier()
dtree=GridSearchCV(tree,params,scoring='precision',cv=kfold,n_jobs=-1)

In [30]:
dtree.fit(X_train,y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': range(5, 25, 5),
                         'min_samples_leaf': range(50, 250, 50),
                         'min_samples_split': range(50, 250, 50)},
             scoring='precision')

In [31]:
y_test_pred_dt=dtree.predict(X_test)

In [32]:
print(accuracy_score(y_test,y_test_pred_dt))
print(confusion_matrix(y_test,y_test_pred_dt))
print(classification_report(y_test,y_test_pred_dt))

0.9993914071369217
[[85262    20]
 [   32   129]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85282
           1       0.87      0.80      0.83       161

    accuracy                           1.00     85443
   macro avg       0.93      0.90      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [33]:
#Random Forest

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [38]:
y_test_pred_rf=rfc.predict(X_test)

In [39]:
print(accuracy_score(y_test,y_test_pred_rf))
print(confusion_matrix(y_test,y_test_pred_rf))
print(classification_report(y_test,y_test_pred_rf))

0.9994733330992591
[[85271    11]
 [   34   127]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85282
           1       0.92      0.79      0.85       161

    accuracy                           1.00     85443
   macro avg       0.96      0.89      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [40]:
param_grid = {
    'max_depth': [4,8,10],
    'min_samples_leaf': range(100, 400, 200),
    'min_samples_split': range(200, 500, 200),
    'n_estimators': [100,200, 300], 
    'max_features': [5, 10]
}
# Create a based model
rf = RandomForestClassifier()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, scoring='precision',
                          cv = 3, n_jobs = -1,verbose = 1)

In [41]:
grid_search.fit(X_train,y_train)

Fitting 3 folds for each of 72 candidates, totalling 216 fits


GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [4, 8, 10], 'max_features': [5, 10],
                         'min_samples_leaf': range(100, 400, 200),
                         'min_samples_split': range(200, 500, 200),
                         'n_estimators': [100, 200, 300]},
             scoring='precision', verbose=1)

In [42]:
y_test_pred_rfc=grid_search.predict(X_test)

In [43]:
print(accuracy_score(y_test,y_test_pred_rfc))
print(confusion_matrix(y_test,y_test_pred_rfc))
print(classification_report(y_test,y_test_pred_rfc))

0.9990637032875719
[[85273     9]
 [   71    90]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85282
           1       0.91      0.56      0.69       161

    accuracy                           1.00     85443
   macro avg       0.95      0.78      0.85     85443
weighted avg       1.00      1.00      1.00     85443



In [44]:
#Using class weight in rf

In [45]:
class_weight=dict({0:1,1:500})

In [46]:
rfc=RandomForestClassifier(class_weight=class_weight)
rfc.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 500})

In [47]:
y_test_pred_rf=rfc.predict(X_test)
print(accuracy_score(y_test,y_test_pred_rf))
print(confusion_matrix(y_test,y_test_pred_rf))
print(classification_report(y_test,y_test_pred_rf))

0.9995084442259752
[[85275     7]
 [   35   126]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85282
           1       0.95      0.78      0.86       161

    accuracy                           1.00     85443
   macro avg       0.97      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443



In [21]:
from imblearn.under_sampling import NearMiss
ns=NearMiss(1)
X_train_ns,y_train_ns=ns.fit_sample(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=1 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


In [22]:
y_train.value_counts()

0    199019
1       345
Name: Class, dtype: int64

In [23]:
y_train_ns.value_counts()

0    345
1    345
Name: Class, dtype: int64

In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
kfold=KFold(n_splits=5,shuffle=False)
#Lets use decision tree for sample
params={'max_depth': range(5, 25, 5),
    'min_samples_leaf': range(50, 250, 50),
    'min_samples_split': range(50, 250, 50),
    'criterion': ["entropy", "gini"]}
tree=DecisionTreeClassifier()
dtree=GridSearchCV(tree,params,scoring='precision',cv=kfold,n_jobs=-1)
dtree.fit(X_train_ns,y_train_ns)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': range(5, 25, 5),
                         'min_samples_leaf': range(50, 250, 50),
                         'min_samples_split': range(50, 250, 50)},
             scoring='precision')

In [26]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
y_test_pred_dt=dtree.predict(X_test)
print(accuracy_score(y_test,y_test_pred_dt))
print(confusion_matrix(y_test,y_test_pred_dt))
print(classification_report(y_test,y_test_pred_dt))

0.431808340062966
[[36760 48536]
 [   12   135]]
              precision    recall  f1-score   support

           0       1.00      0.43      0.60     85296
           1       0.00      0.92      0.01       147

    accuracy                           0.43     85443
   macro avg       0.50      0.67      0.30     85443
weighted avg       1.00      0.43      0.60     85443



In [27]:
#Oversampling
from imblearn.over_sampling import RandomOverSampler
os=RandomOverSampler(1)
X_train_os,y_train_os=os.fit_sample(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=1 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
kfold=KFold(n_splits=5,shuffle=False)
#Lets use decision tree for sample
params={'max_depth': range(5, 25, 5),
    'min_samples_leaf': range(50, 250, 50),
    'min_samples_split': range(50, 250, 50),
    'criterion': ["entropy", "gini"]}
tree=DecisionTreeClassifier()
dtree=GridSearchCV(tree,params,scoring='precision',cv=kfold,n_jobs=-1)
dtree.fit(X_train_os,y_train_os)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': range(5, 25, 5),
                         'min_samples_leaf': range(50, 250, 50),
                         'min_samples_split': range(50, 250, 50)},
             scoring='precision')

In [29]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
y_test_pred_dt=dtree.predict(X_test)
print(accuracy_score(y_test,y_test_pred_dt))
print(confusion_matrix(y_test,y_test_pred_dt))
print(classification_report(y_test,y_test_pred_dt))

0.9972145172805262
[[85089   207]
 [   31   116]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.36      0.79      0.49       147

    accuracy                           1.00     85443
   macro avg       0.68      0.89      0.75     85443
weighted avg       1.00      1.00      1.00     85443



In [31]:
#SMOTE
from imblearn.combine import SMOTETomek

In [32]:
smo=SMOTETomek(1)
X_train_smo,y_train_smo=smo.fit_sample(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=1 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


In [33]:
tree=DecisionTreeClassifier()
tree.fit(X_train_smo,y_train_smo)

DecisionTreeClassifier()

In [34]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
y_test_pred_dt=tree.predict(X_test)
print(accuracy_score(y_test,y_test_pred_dt))
print(confusion_matrix(y_test,y_test_pred_dt))
print(classification_report(y_test,y_test_pred_dt))

0.9979284435237527
[[85154   142]
 [   35   112]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.44      0.76      0.56       147

    accuracy                           1.00     85443
   macro avg       0.72      0.88      0.78     85443
weighted avg       1.00      1.00      1.00     85443

